/* Cable: CMake Bootstrap Library.
 * Copyright 2018 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0. See the LICENSE file.
 */

/* Generated by Cable Build Info on 2018-07-06T11:02:19. Do not modify directly. */

#include "eth-buildinfo.h"

const struct buildinfo* eth_get_buildinfo()
{
    static const struct buildinfo buildinfo = {
        .project_version = "1.3.0-20502+commit.74ed433f.dirty",
        .git_commit_hash = "74ed433f9af68505f670d3e708a4f888daf2d7f0",
        .system_name = "linux",
        .system_processor = "x86_64",
        .compiler_id = "gnu",
        .compiler_version = "5.4.0",
        .build_type = "relwithdebinfo",
    };
    return &buildinfo;
}
